name: adoptopenjdk
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 6"
  push:
    paths:
      - "adoptopenjdk/**"
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push
        run: |
          set -eux;
          for file_path in $(find adoptopenjdk -name Dockerfile | sort -r | head -n 3);
          do
            /usr/bin/docker buildx prune -a -f
            /usr/bin/docker buildx build --push --no-cache \
              --platform linux/amd64,linux/arm64 \
              --file ${file_path} \
              --tag ghcr.io/${{ github.repository_owner }}/onecontract-cloud_$(dirname $file_path | sed 's / : g') \
              ${file_path%/*}
          done
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
