name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      retain_days:
        description: "Number of days."
        required: true
        default: 7
  schedule:
    - cron: "0 16 * * *"
jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          retain_days: ${{ github.event.inputs.retain_days }}
