name: Sync images to Tencent
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  ghcr-to-tencent:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
    steps:
      - name: Ghcr to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - carllhw/onecontract-cloud_elasticsearch
                - carllhw/onecontract-cloud_javabase
                - carllhw/onecontract-cloud_kibana
          sync-policy:
            from: ghcr
            to: tencentyun
            dry-run: false
            replace:
              - old: carllhw/onecontract-cloud_
                new: onecontract-cloud/
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
  dockerhub-to-tencent:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
    steps:
      - name: Dockerhub to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - library/mysql:5.7.35
                - library/redis:5.0.13
                - library/busybox:1.33.1
                - istio/install-cni:1.11.3
                - istio/operator:1.11.3
                - istio/pilot:1.11.3
                - istio/proxyv2:1.11.3
                - minio/minio:RELEASE.2021-08-25T00-41-18Z
                - hengyunabc/arthas:3.5.4-no-jdk
                - apache/skywalking-oap-server:8.7.0-es7
                - apache/skywalking-ui:8.7.0
                - apache/skywalking-java-agent:8.7.0-alpine
                - jimmidyson/configmap-reload:v0.5.0
                - jettech/kube-webhook-certgen:v1.5.2
          sync-policy:
            from: dockerhub
            to: tencentyun
            dry-run: false
            replace:
              - old: library
                new: onecontract-cloud
              - old: istio/
                new: onecontract-cloud/istio_
              - old: minio/
                new: onecontract-cloud/minio_
              - old: apache/
                new: onecontract-cloud/apache_
              - old: hengyunabc/
                new: onecontract-cloud/hengyunabc_
              - old: jimmidyson/
                new: onecontract-cloud/jimmidyson_
              - old: jettech/
                new: onecontract-cloud/jettech_
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
  quay-to-tencent:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
    steps:
      - name: Quay to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            quay:
              registry: https://quay.io
              repositories:
                - prometheus/prometheus:v2.30.0
                - prometheus/node-exporter:v1.2.2
                - prometheus/alertmanager:v0.23.0
                - prometheus/pushgateway:v1.4.1
          sync-policy:
            from: quay
            to: tencentyun
            dry-run: false
            replace:
              - old: prometheus/
                new: onecontract-cloud/prometheus_
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
  gcr-to-tencent:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
    steps:
      - name: Gcr to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://k8s.gcr.io
              repositories:
                - ingress-nginx/controller:v1.0.2
                - kube-state-metrics/kube-state-metrics:v2.2.1
          sync-policy:
            from: gcr
            to: tencentyun
            dry-run: false
            replace:
              - old: ingress-nginx/
                new: onecontract-cloud/ingress-nginx_
              - old: kube-state-metrics/
                new: onecontract-cloud/prometheus_
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
