# ref: https://github.com/TimeBye/registry-manager
name: Sync images to Dockerhub
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
jobs:
  ghcr-to-dockerhub:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Ghcr to Dockerhub force
        run: |
          cat << EOF >config.yaml
          registries:
            dockerhub:
              registry: https://registry-1.docker.io
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - carllhw/onecontract-cloud_applicationinsights-agent
                - carllhw/onecontract-cloud_arms-agent
                - carllhw/onecontract-cloud_elasticsearch
                - carllhw/onecontract-cloud_frontbase
                - carllhw/onecontract-cloud_javabase
                - carllhw/onecontract-cloud_jnlp-agent-python
                - carllhw/onecontract-cloud_kibana
                - carllhw/onecontract-cloud_mysql-backup
                - carllhw/onecontract-cloud_openvpn
                - carllhw/onecontract-cloud_rclone
                - carllhw/onecontract-cloud_rustbase
          sync-policy:
            from: ghcr
            to: tencentyun
            force: true
            dry-run: false
            replace:
              - old: carllhw/onecontract-cloud_
                new: onecontract/
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
