name: Sync images to Tencent
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  ghcr-to-tencent:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
    steps:
      - name: Ghcr to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - carllhw/onecontract-cloud_elasticsearch
                - carllhw/onecontract-cloud_javabase
                - carllhw/onecontract-cloud_kibana
          sync-policy:
            from: ghcr
            to: tencentyun
            dry-run: false
            replace:
              - old: carllhw/onecontract-cloud_
                new: onecontract-cloud/
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
  dockerhub-to-tencent:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
    steps:
      - name: Dockerhub to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - library/mysql:5.7.35
                - library/redis:5.0.13
                - istio/install-cni:1.11.2
                - istio/operator:1.11.2
                - istio/pilot:1.11.2
                - istio/proxyv2:1.11.2
                - minio/minio:RELEASE.2021-08-25T00-41-18Z
                - hengyunabc/arthas:3.5.2-no-jdk
                - apache/skywalking-oap-server:8.7.0-es7
                - apache/skywalking-ui:8.7.0
                - apache/skywalking-java-agent:8.7.0-alpine
          sync-policy:
            from: dockerhub
            to: tencentyun
            dry-run: false
            replace:
              - old: library
                new: onecontract-cloud
              - old: istio/
                new: onecontract-cloud/istio-
              - old: minio/minio
                new: onecontract-cloud/minio
              - old: hengyunabc/arthas
                new: onecontract-cloud/arthas
              - old: apache/skywalking-oap-server
                new: onecontract-cloud/skywalking-oap-server
              - old: apache/skywalking-ui
                new: onecontract-cloud/skywalking-ui
              - old: apache/skywalking-java-agent
                new: onecontract-cloud/skywalking-java-agent
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
