name: Sync images to Tencent
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  ghcr-to-tencent:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
    steps:
      - name: Ghcr to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            aliyuncs:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - carllhw/onecontract-cloud_elasticsearch
          sync-policy:
            from: ghcr
            to: aliyuncs
            dry-run: false
            replace:
              - old: carllhw/onecontract-cloud_
                new: onecontract-cloud/
            filters:
              - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          registry-manager sync -c config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3
